// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data
{
    public partial class Event
    {
        public Event()
        {
            EventDetail = new HashSet<EventDetail>();
        }

        [Key]
        [Column("EventsID")]
        public long EventsId { get; set; }
        [Column("FK_TournamentID")]
        public long FkTournamentId { get; set; }
        [Required]
        [StringLength(100)]
        public string EventName { get; set; }
        public short EventNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EventDateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EventEndDateTime { get; set; }
        public bool AutoClose { get; set; }
        public bool IsDelete { get; set; }

        [ForeignKey(nameof(FkTournamentId))]
        [InverseProperty(nameof(Tournament.Event))]
        public virtual Tournament FkTournament { get; set; }
        [InverseProperty("FkEvent")]
        public virtual ICollection<EventDetail> EventDetail { get; set; }
    }
}