// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data
{
    public class EventDetailStatusConfiguration : IEntityTypeConfiguration<EventDetailStatus>
    {
        public void Configure(EntityTypeBuilder<EventDetailStatus> entity)
        {
            entity.Property(e => e.EventDetailsStatusName).IsUnicode(false);
        }
    }
}
