// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data
{
    public partial class EventDetailStatus
    {
        public EventDetailStatus()
        {
            EventDetail = new HashSet<EventDetail>();
        }

        [Key]
        [Column("EventDetailsStatusID")]
        public short EventDetailsStatusId { get; set; }
        [Required]
        [StringLength(50)]
        public string EventDetailsStatusName { get; set; }

        [InverseProperty("FkEventDetailStatus")]
        public virtual ICollection<EventDetail> EventDetail { get; set; }
    }
}