// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data
{
    public class EventDetailConfiguration : IEntityTypeConfiguration<EventDetail>
    {
        public void Configure(EntityTypeBuilder<EventDetail> entity)
        {
            entity.Property(e => e.EventDetailName).IsUnicode(false);

            entity.HasOne(d => d.FkEventDetailStatus)
                .WithMany(p => p.EventDetail)
                .HasForeignKey(d => d.FkEventDetailStatusId)
                .HasConstraintName("FK_EventDetail_EventDetailStatus");

            entity.HasOne(d => d.FkEvent)
                .WithMany(p => p.EventDetail)
                .HasForeignKey(d => d.FkEventId)
                .HasConstraintName("FK_EventDetail_Event");
        }
    }
}
