// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data
{
    public class EventConfiguration : IEntityTypeConfiguration<Event>
    {
        public void Configure(EntityTypeBuilder<Event> entity)
        {
            entity.Property(e => e.EventName).IsUnicode(false);

            entity.HasOne(d => d.FkTournament)
                .WithMany(p => p.Event)
                .HasForeignKey(d => d.FkTournamentId)
                .HasConstraintName("FK_Event_Tournament");
        }
    }
}
