// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading.Tasks;
using Data;

namespace Data
{
    public partial class HollywoodtestContextProcedures
    {
        private readonly HollywoodtestContext _context;

        public HollywoodtestContextProcedures(HollywoodtestContext context)
        {
            _context = context;
        }

        public async Task<int> UpdateEventDetailStatus(long? EventDetailID,long? EventDetailsStatusID)
        {
            var parameterEventDetailID = new SqlParameter
            {
                ParameterName = "EventDetailID",
                Precision = 19,
                Size = 8,
                SqlDbType = System.Data.SqlDbType.BigInt,
                Value = EventDetailID,
            };

            var parameterEventDetailsStatusID = new SqlParameter
            {
                ParameterName = "EventDetailsStatusID",
                Precision = 19,
                Size = 8,
                SqlDbType = System.Data.SqlDbType.BigInt,
                Value = EventDetailsStatusID,
            };

            return await _context.Database.ExecuteSqlRawAsync("EXEC [dbo].[UpdateEventDetailStatus] @EventDetailID,@EventDetailsStatusID  ",parameterEventDetailID,parameterEventDetailsStatusID);
        }
    }
}
