// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class UpdateEventDetailStatusResult
    {
    }
}
